


WWW_Files=data.html default.aspx
WWW_Dir=//research/Root/web/external/http/research/netres/projects/VanLAN/

FTP_Files=README.txt
FTP_Dir=//research/Root/web/external/ftp/pub/ratul/VanLAN-imc07/


WWW: 
	cp ${WWW_Files} ${WWW_Dir}

FTP: 
	cp ${FTP_Files} ${FTP_Dir}

